#! python 
# -*- coding: utf-8 -*-
# 

# Autogenerated by Coventor SEMulator3D on 11/10/2023, 15:35:40
# SEMulator3D 

# Using model file:        D:\SEMulator 3D\Assignment11_FinFET_Inverter\FinFET_Inverter.zam
# Using process file:      D:/SEMulator 3D/Assignment11_FinFET_Inverter/FinFET_Inverter-Input/FinFET_Inverter.vproc
# Using analysis file:     D:/SEMulator 3D/Assignment11_FinFET_Inverter/FinFET_Inverter-Input/FinFET_Inverter.vanalysis
# Using material file:     D:/SEMulator 3D/Assignment11_FinFET_Inverter/FinFET_Inverter-Input/SEMulator3DMaterialsDatabase11.vmpd
# Using layout file:       D:/SEMulator 3D/Assignment11_FinFET_Inverter/FinFET_Inverter-Input/FinFET_Inverter.gds

# ============================================================== 
# Command line arguments
import sys
import getopt
from voxelDocument import MonitorKillFile

opts, args = getopt.getopt(sys.argv[1:], '', ["fpw=","mpw=","spw=","encrypted","killFile="])

fpw, mpw, spw = '', '', ''
encrypted = False
for opt, arg in opts:
   if opt == "--fpw":
      fpw = arg
   elif opt == "--mpw":
      mpw = arg
   elif opt == "--spw":
      spw = arg
   elif opt == "--encrypted":
      encrypted = True
   elif opt == "--killFile":
      MonitorKillFile(arg)
# ============================================================== 
# Choose our python API version
_SEMulator3D_API_VERSION = '11.0'

# ============================================================== 
# Import Python built-in modules
import math
import time
import traceback
import logging

# Import SEMulator3D modules
from voxelModeler import *

# Logging
_log = logging.getLogger("cov.modelBuilding")
startTime = time.time()

#============================================================== 
# Setup Masks 
layoutFile = 'D:/SEMulator 3D/Assignment11_FinFET_Inverter/FinFET_Inverter-Input/FinFET_Inverter.gds'
layoutTopCell = 'FinFET_Inverter'

# GDS layer map info
layerMap = {}
layerMap['CD_width_sidewall'] = (6, 0)
layerMap['Drain_Via'] = (12, 0)
layerMap['Fin_Pattern'] = (0, 0)
layerMap['Gate_Via'] = (10, 0)
layerMap['Inverter_Input'] = (11, 0)
layerMap['Inverter_Output'] = (13, 0)
layerMap['NMOS_Gate'] = (3, 0)
layerMap['NMOS_S_D_implantation'] = (2, 0)
layerMap['PMOS_Gate'] = (9, 0)
layerMap['PMOS_S_D_Implantation'] = (8, 0)
layerMap['boundary'] = (1, 0)
layerMap['sidewall'] = (7, 0)
layerMap['spacer'] = (4, 0)


#============================================================== 
# Setup Modeler and Documents
modelResolution = 1
modelUnits = 'nm'

voxDoc = VoxelDocument('D:/SEMulator 3D/Assignment11_FinFET_Inverter/FinFET_Inverter.zam', modelResolution, modelUnits, LOAD)

modeler = VoxelModeler(voxDoc)

# Active masks in the process
activeLayoutMaskNames = ('Drain_Via', 'Fin_Pattern', 'Gate', 'Gate_Via', 'Inverter_Input', 'Inverter_Output', 'NMOS_Gate', 'NMOS_S_D_implantation', 'PMOS_Gate', 'PMOS_S_D_Implantation', 'boundary', 'spacer', )
maskFile = MaskFile(layoutFile, layoutTopCell)

modeler.SetDefaultMaskUnitsPerMicron(maskFile.GetUnitsPerMicron())

for maskName in activeLayoutMaskNames:
    if maskName in layerMap.keys():
        mask = maskFile.GetLayerWithDataType(layerMap[maskName][0], layerMap[maskName][1])
        mask.SetName(maskName)
        modeler.AddActiveMask(mask)

# Fix build boundary based on current masks.
modeler.CacheBuildBoundary()


#============================================================== 
# Load Process 
procDoc = CProcessData.ProcessDocument()
procDoc.openWithPasswords('D:/SEMulator 3D/Assignment11_FinFET_Inverter/FinFET_Inverter-Input/FinFET_Inverter.vproc', fpw, mpw, encrypted)

#============================================================== 
# Load Analysis 
analysisDoc = CProcessData.AnalysisDocument()
analysisDoc.openWithPasswords('D:/SEMulator 3D/Assignment11_FinFET_Inverter/FinFET_Inverter-Input/FinFET_Inverter.vanalysis', fpw, mpw, encrypted)

#============================================================== 
# Setup Materials and Dopants
matDoc = CMaterialData.MaterialDocument()
matDoc.openWithPasswords('D:/SEMulator 3D/Assignment11_FinFET_Inverter/FinFET_Inverter-Input/SEMulator3DMaterialsDatabase11.vmpd', fpw, mpw, encrypted)
for mat in matDoc.getActiveMaterialsInProcess(procDoc):
    voxDoc.GetMaterials().Add(mat, DUP_ADD_ALLOW)

for dopant in matDoc.getActiveDopantsInProcess(procDoc):
    voxDoc.GetDopants().Add(dopant, DUP_ADD_ALLOW)

if analysisDoc:
    for mat in matDoc.getActiveMaterialsInProcess(analysisDoc):
        voxDoc.GetMaterials().Add(mat, DUP_ADD_ALLOW)
    
    for dopant in matDoc.getActiveDopantsInProcess(analysisDoc):
        voxDoc.GetDopants().Add(dopant, DUP_ADD_ALLOW)

success = voxDoc.GetProperties().IsModelBuildComplete() #True

#============================================================== 
# Build Model
success = modeler.BuildModel(procDoc, analysisDoc, spw)

#============================================================== 
# Save Model Build
if not voxDoc.IsOutputEnabled():
    modeler.SaveFinalStep()

voxDoc.GetProperties().SetModelBuildComplete(success)
voxDoc.Save()

endTime = time.time()
_log.info('Build process completed.')
_log.info('Elapsed Time %d seconds.', (endTime-startTime))

if voxDoc.GetProperties().GetStartViewer():
    voxDoc.StartViewer(False)

if not success:
    # Though the build terminated cleanly, it was not considered successful.
    sys.exit(1)

