#! python 
# -*- coding: utf-8 -*-
# 

# Autogenerated by Coventor SEMulator3D on 11/8/2023, 1:6:30
# SEMulator3D 

# Using model file:        C:\Simulator3d Projects\Assignment_10_3DNAND_16L\FW_ 3D NAND 16 L model\3DNAND_16L_v11\3DNAND_16L.zam
# Using process file:      C:/Simulator3d Projects/Assignment_10_3DNAND_16L/FW_ 3D NAND 16 L model/3DNAND_16L_v11/3DNAND_16L-Input/TCAT_16L.vproc
# Using analysis file:     C:/Simulator3d Projects/Assignment_10_3DNAND_16L/FW_ 3D NAND 16 L model/3DNAND_16L_v11/3DNAND_16L-Input/TCAT_16L_ana.vanalysis
# Using material file:     C:/Simulator3d Projects/Assignment_10_3DNAND_16L/FW_ 3D NAND 16 L model/3DNAND_16L_v11/3DNAND_16L-Input/SEMulator3DMaterialsDatabase6.vmpd
# Using layout file:       C:/Simulator3d Projects/Assignment_10_3DNAND_16L/FW_ 3D NAND 16 L model/3DNAND_16L_v11/3DNAND_16L-Input/3DNAND_16L.gds

# ============================================================== 
# Command line arguments
import sys
import getopt
from voxelDocument import MonitorKillFile

opts, args = getopt.getopt(sys.argv[1:], '', ["fpw=","mpw=","spw=","encrypted","killFile="])

fpw, mpw, spw = '', '', ''
encrypted = False
for opt, arg in opts:
   if opt == "--fpw":
      fpw = arg
   elif opt == "--mpw":
      mpw = arg
   elif opt == "--spw":
      spw = arg
   elif opt == "--encrypted":
      encrypted = True
   elif opt == "--killFile":
      MonitorKillFile(arg)
# ============================================================== 
# Choose our python API version
_SEMulator3D_API_VERSION = '11.0'

# ============================================================== 
# Import Python built-in modules
import math
import time
import traceback
import logging

# Import SEMulator3D modules
from voxelModeler import *

# Logging
_log = logging.getLogger("cov.modelBuilding")
startTime = time.time()

#============================================================== 
# Setup Masks 
layoutFile = 'C:/Simulator3d Projects/Assignment_10_3DNAND_16L/FW_ 3D NAND 16 L model/3DNAND_16L_v11/3DNAND_16L-Input/3DNAND_16L.gds'
layoutTopCell = '3DNAND16L_TOP'

# GDS layer map info
layerMap = {}
layerMap['AREA_CONTACT2'] = (30, 0)
layerMap['BB'] = (0, 0)
layerMap['BB_10'] = (51, 0)
layerMap['BB_11'] = (52, 0)
layerMap['BB_2'] = (5, 0)
layerMap['BB_3'] = (9, 0)
layerMap['BB_4'] = (19, 0)
layerMap['BB_5'] = (35, 0)
layerMap['BB_6'] = (45, 0)
layerMap['BB_7'] = (47, 0)
layerMap['BB_8'] = (48, 0)
layerMap['BB_9'] = (50, 0)
layerMap['BB_ALL'] = (31, 0)
layerMap['BB_WL'] = (49, 0)
layerMap['BL'] = (8, 0)
layerMap['CD_CHANNEL'] = (10, 0)
layerMap['CD_CHANNEL2'] = (12, 0)
layerMap['CD_CHANNEL3'] = (13, 0)
layerMap['CD_CONTACT1'] = (11, 0)
layerMap['CD_CONTACT10'] = (37, 0)
layerMap['CD_CONTACT11'] = (38, 0)
layerMap['CD_CONTACT12'] = (39, 0)
layerMap['CD_CONTACT13'] = (40, 0)
layerMap['CD_CONTACT14'] = (41, 0)
layerMap['CD_CONTACT15'] = (42, 0)
layerMap['CD_CONTACT16'] = (43, 0)
layerMap['CD_CONTACT17'] = (44, 0)
layerMap['CD_CONTACT2'] = (17, 0)
layerMap['CD_CONTACT3'] = (21, 0)
layerMap['CD_CONTACT4'] = (22, 0)
layerMap['CD_CONTACT5'] = (23, 0)
layerMap['CD_CONTACT6'] = (24, 0)
layerMap['CD_CONTACT7'] = (25, 0)
layerMap['CD_CONTACT8'] = (26, 0)
layerMap['CD_CONTACT9'] = (29, 0)
layerMap['CD_CSL1'] = (14, 0)
layerMap['CD_CSL2'] = (15, 0)
layerMap['CD_SSL'] = (20, 0)
layerMap['CD_WL1'] = (16, 0)
layerMap['CHANNEL_HOLE'] = (2, 0)
layerMap['CONTACT'] = (3, 0)
layerMap['CONTACT_Via2'] = (27, 0)
layerMap['CROP_AFM'] = (33, 0)
layerMap['CSL1'] = (1, 0)
layerMap['CSL2'] = (6, 0)
layerMap['Cutout'] = (46, 0)
layerMap['M2'] = (28, 0)
layerMap['MEA_AFM_GATE'] = (34, 0)
layerMap['MEA_AFM_STAIRCASE'] = (36, 0)
layerMap['MEA_TOPFILM'] = (32, 0)
layerMap['PAD_0'] = (4, 0)
layerMap['SSL_Line'] = (18, 0)
layerMap['WL'] = (7, 0)


#============================================================== 
# Setup Modeler and Documents
modelResolution = 2
modelUnits = 'nm'

voxDoc = VoxelDocument('C:/Simulator3d Projects/Assignment_10_3DNAND_16L/FW_ 3D NAND 16 L model/3DNAND_16L_v11/3DNAND_16L.zam', modelResolution, modelUnits, LOAD)

modeler = VoxelModeler(voxDoc)

# Active masks in the process
activeLayoutMaskNames = ('BB_ALL', 'CD_CHANNEL', 'CD_CSL2', 'CD_SSL', 'CHANNEL_HOLE', 'CONTACT', 'CSL', 'CSL1', 'CSL2', 'PAD_0', 'THK_Base', )
maskFile = MaskFile(layoutFile, layoutTopCell)

modeler.SetDefaultMaskUnitsPerMicron(maskFile.GetUnitsPerMicron())

for maskName in activeLayoutMaskNames:
    if maskName in layerMap.keys():
        mask = maskFile.GetLayerWithDataType(layerMap[maskName][0], layerMap[maskName][1])
        mask.SetName(maskName)
        modeler.AddActiveMask(mask)

# Fix build boundary based on current masks.
modeler.CacheBuildBoundary()


#============================================================== 
# Load Process 
procDoc = CProcessData.ProcessDocument()
procDoc.openWithPasswords('C:/Simulator3d Projects/Assignment_10_3DNAND_16L/FW_ 3D NAND 16 L model/3DNAND_16L_v11/3DNAND_16L-Input/TCAT_16L.vproc', fpw, mpw, encrypted)

#============================================================== 
# Load Analysis 
analysisDoc = CProcessData.AnalysisDocument()
analysisDoc.openWithPasswords('C:/Simulator3d Projects/Assignment_10_3DNAND_16L/FW_ 3D NAND 16 L model/3DNAND_16L_v11/3DNAND_16L-Input/TCAT_16L_ana.vanalysis', fpw, mpw, encrypted)

#============================================================== 
# Setup Materials and Dopants
matDoc = CMaterialData.MaterialDocument()
matDoc.openWithPasswords('C:/Simulator3d Projects/Assignment_10_3DNAND_16L/FW_ 3D NAND 16 L model/3DNAND_16L_v11/3DNAND_16L-Input/SEMulator3DMaterialsDatabase6.vmpd', fpw, mpw, encrypted)
for mat in matDoc.getActiveMaterialsInProcess(procDoc):
    voxDoc.GetMaterials().Add(mat, DUP_ADD_ALLOW)

for dopant in matDoc.getActiveDopantsInProcess(procDoc):
    voxDoc.GetDopants().Add(dopant, DUP_ADD_ALLOW)

if analysisDoc:
    for mat in matDoc.getActiveMaterialsInProcess(analysisDoc):
        voxDoc.GetMaterials().Add(mat, DUP_ADD_ALLOW)
    
    for dopant in matDoc.getActiveDopantsInProcess(analysisDoc):
        voxDoc.GetDopants().Add(dopant, DUP_ADD_ALLOW)

success = voxDoc.GetProperties().IsModelBuildComplete() #True

#============================================================== 
# Build Model
success = modeler.BuildModel(procDoc, analysisDoc, spw)

#============================================================== 
# Save Model Build
if not voxDoc.IsOutputEnabled():
    modeler.SaveFinalStep()

voxDoc.GetProperties().SetModelBuildComplete(success)
voxDoc.Save()

endTime = time.time()
_log.info('Build process completed.')
_log.info('Elapsed Time %d seconds.', (endTime-startTime))

if voxDoc.GetProperties().GetStartViewer():
    voxDoc.StartViewer(False)

if not success:
    # Though the build terminated cleanly, it was not considered successful.
    sys.exit(1)

